steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/programmierprojekt:$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/programmierprojekt:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "programmierprojekt"
      - "--image"
      - "gcr.io/$PROJECT_ID/programmierprojekt:$COMMIT_SHA"
      - "--region"
      - "europe-west4"
      - "--port"
      - "80" # Dieser Schritt weist Cloud Run an, den Port 80 zu verwenden
images:
  - "gcr.io/$PROJECT_ID/programmierprojekt:$COMMIT_SHA"
  

  
