#!!!! cloudbuild.yaml Datei für development- bei merge mit main-branch "development" durch "programmierprojekt" ersetzten !!!!
#  (oder cloudbuild.yaml des main-branch beibehalten)

steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/development:$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/development:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "development"
      - "--image"
      - "gcr.io/$PROJECT_ID/development:$COMMIT_SHA"
      - "--region"
      - "europe-west4"
      - "--port"
      - "80" # Dieser Schritt weist Cloud Run an, den Port 80 zu verwenden
images:
  - "gcr.io/$PROJECT_ID/development:$COMMIT_SHA"
