name: Python Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Wählen Sie die Python-Version, die Sie benötigen

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Stellen Sie sicher, dass Ihre Anforderungen installiert sind
        pip install pytest

    - name: Run tests
      run: |
        pytest UnitTests.py  # Hier haben wir den Befehl angepasst, um Ihre Tests auszuführen
